### ISSUE TITLE
chart-data-updater doesn't work on Bar chart

### ISSUE THREAD

**Issue by pierrickrouxel** [aomra015/ember-cli-chart#13]
Hi

I try to use your component with Bar chart. When I update data it runs the method `updateLinearCharts` from chart-data-updater.js.

It fails on chart.segments because this property seems to be undefined for Bar chart.

**Comment by pierrickrouxel** [comment]
I found the reason. I try to update my graph from 1 dataset to 3. Your implementation tries to update values of already drawn datasets but doesn't add news.

**Comment by skyuplam** [comment]
+1

**Comment by aomra015** [comment]
Thanks for reporting this. I think I know where the bug is. I'll try to get to this asap.

**Comment by aomra015** [comment]
Do you mind verifying that the following branch fixes this? https://github.com/aomra015/ember-cli-chart/pull/16

I'm redrawing the chart if the dataset changes too much. Simple data changes will get updated though.

**Comment by pierrickrouxel** [comment]
Thank you !
