### ISSUE TITLE
Chart Update not working with dynamic segements in routes

### ISSUE THREAD

**Issue by bbooth** [aomra015/ember-cli-chart#14]
I have a chart on a template that has data provided by the model of the specific route.  This route contains a dynamic segment.  Since the view is never really rerendered on navigating between models of the same route.

I created property observers on the model which does cause the chart to update its data points, but sometimes the model has a different data set with different labels.  Example a bar chart on a route like /item/1 looks like:

labels: ["Category 1", "Category 2", "Category 3"],
datasets: [
    {
        data: [1,3,5]
    }
]

route /item/2 looks like:
labels: ["Category 4", "Category 5", "Category 6", "Category 7"],
datasets: [
    {
        data: [2,4,6,8]
    }
]

The labels don't change nor other chart options like chart colors, and when the datasets have a different lengths of arrays, things get screwed up as well.  I can create a sample if needed.  I have forked the repo as well and trying to fix it to help out.

**Comment by aomra015** [comment]
Yeah there's a bug preventing bar charts from updating properly. Chartjs right now doesn't provide an easy way of doing this. 

I have a fix that will probably go out this weekend. The fix involves redrawing the chart if the datasets change too much.

Updating bar charts live and updating existing bar points is easy enough. Adding new points, labels, etc is a pain.

**Comment by bbooth** [comment]
Yeah, I saw the other issue.  One thing if it helps if I navigate to another unrelated route then back the chart redraws properly, because I think Ember is destroying the chart when it transitions to a new route..

**Comment by aomra015** [comment]
Yeah honestly right now I'm leaning towards just destroying the chart and redrawing it (like ember is doing in the case you described) if the dataset changes too much. Otherwise we would be writing complicated code to keep the chart updating properly.

In fact I think a lot of this dynamic updating should be done by Chartjs directly and not by this addon.

**Comment by bbooth** [comment]
That is precisely what I did as work around.  I ditched the chart updater and just destroyed the previous chart instance before recreating (was getting strange overlaying charts).  Here is the commit if you want to check it out.  I can also send over a PR if you want.

ad134a3b1d534b0e60979af777c6005819eaac09
