### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by dthul** [aomra015/ember-cli-chart#17]
I use ember-cli v0.2.3 and when I run the command `ember install ember-cli-chart` I get the following error message:

    The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

**Comment by aomra015** [comment]
This seems to be a problem with ember-cli -- https://github.com/ember-cli/ember-cli/issues/3831

Supposedly the addon installs even with that error. Is that true @dthul ?

**Comment by dthul** [comment]
I had to issue `ember g ember-cli-chart` to get it to work, otherwise it complained about a missing component.

**Comment by aomra015** [comment]
Yeah that generator adds Chartjs through bower.

**Comment by lucascampbell** [comment]
`ember install:addon ember-cli-chart` seems to work with ember cli 0.2.0

**Comment by aomra015** [comment]
With the latest ember-cli (0.2.7) `ember install ember-cli-chart` seems to work; the addon and blueprint run properly. With older versions of ember-cli it's probably safer to use `ember install:addon ember-cli-chart`.
