### ISSUE TITLE
Glimmer Support?

### ISSUE THREAD

**Issue by brendanoh** [aomra015/ember-cli-chart#18]
Is anyone using this with the latest Ember-CLI and Glimmer version of Ember beta?

In Chart Data Updater:

 var chart = this.get('chart'); 

chart is always undefined.

**Comment by aomra015** [comment]
@brendanoh I haven't tested this addon with Ember 1.12 and 1.13. I hope to update to the latest version of emberjs and ember-cli asap. I don't think we're doing anything out of the ordinary in this addon so I don't know why 1.13 would not be backwards compatible.

**Comment by brendanoh** [comment]
Yeah no idea. But this project is not alone. Half the add-ons don't support 1.12 or 1.13.

**Comment by aomra015** [comment]
@tstirrat  described the issue. Looks like a regression in 1.13. It's calling `updateChart` when it shouldn't. That function is an observer that should be fired on data change.

**Comment by tstirrat** [comment]
yep, previously, observer methods needed to append `.on('init')` to be called immediately. looks like that pattern has been broken.

**Comment by aomra015** [comment]
I think the solution here is to add the observer in `didInsertElement` after everything has been initialized. 

```
this.addObserver('data', 'data.[]', 'options', this.updateChart)
```
