### ISSUE TITLE
Legend only works if chart wrapped properly

### ISSUE THREAD

**Issue by jeffreybiles** [aomra015/ember-cli-chart#21]
When using the legend=true option, the ability of the legend to display is dependent upon the parent element of the chart.

```
    if (this.get('legend')) {
      var legend = chart.generateLegend();
      this.$().parent().append(legend);
    }
```

When the parent was the html body, the legend didn't show up.  When I specifically wrapped the chart in a div, it showed up.

There are two ways I see of fixing this

1. Document the requirement
2. Have the legend put inside the chart component

Thanks for writing a great addon, and I hope this helps make it even better!

**Comment by aomra015** [comment]
@jeffreybiles thanks for reporting this!

Option 2 can't be done because the component is a `<canvas>` element so we can't put html in there. So we either document this better or change the component into a `div` with a `canvas` in it.

**Comment by jeffreybiles** [comment]
Awesome, thanks!
