### ISSUE TITLE
Setting global config

### ISSUE THREAD

**Issue by seanttierney** [aomra015/ember-cli-chart#8]
I'd like to set global config for Chart.js.  I have a few different approaches I can take, but I'd like to keep it inline w/ the ember-cli approach. ember-cli-charts documentation doesn't explicitly tell me what the preferred way to set the global config is.

* What is the preferred way to set gobal config? 
* What is the preferred way to set gobla config for a specific chart type? 
* assuming ember-cli-chart is installed via node, what is the correct import statement to extend ember-cli-chart's component?

**Comment by seanttierney** [comment]
@aomra015 thank you for the feedback. Sorry for not responding sooner. I'll review your notes. Thanks again!!

**Comment by aomra015** [comment]
@seanttierney have a look at the latest release. You can now extend the addon:

https://github.com/aomra015/ember-cli-chart/releases/tag/v2.0.0

**Comment by seanttierney** [comment]
@aomra015 so cool, thanks!!
